### ISSUE TITLE
覆盖了上下飞行速度和游戏刻等等，请给出默认纯粹原版的设置

### ISSUE THREAD

**Issue by vocaloidkiss** [lovexyn0827/Minecraft-World-Manipulation-Enchantment-Mod#5]
/messcfg maxClientTicksPerFrame        需要默认不改变原版行为
 /messcfg projectileRandomnessScale  需要默认不改变原版行为 
/messcfg creativeUpwardsSpeed          做一个低等级的mixin，默认不改变原版行为
 /messcfg commandExecutionRequirment  默认需要op
 /messcfg chunkLogAutoArchiving      默认创建文件但不写入

**Comment by lovexyn0827** [comment]
检查了一下，前三个选项的默认设置是与原版等价的，但是文档中的描述确实有些缺漏。

将`commandExecutionRequirment`默认值改为`true`记得已经提了很久了，没想到的是到现在还没有去做[doge]。

`chunkLogAutoArchiving`与`entityLogAutoArchiving`类似，也是一个用于配置内部功能的选项，用于给出在一个存档中使用`/logchunkbehavior`和`/entitylog`时产生的记录文件在退出游戏时会不会被打包成压缩文件（`/logchunkbehavior`有时能在几一分钟内产生接近1GB的记录，但是经过可以被压缩到2MB左右），在没有用到这两条指令时不会被用到。

**Comment by vocaloidkiss** [comment]
creativeUpwardsSpeed覆盖和tweakeroo不太一样，这个上下运动速度无法匹配观察者模式下的水平速度调节，强制锁速度

**Comment by lovexyn0827** [comment]
> creativeUpwardsSpeed覆盖和tweakeroo不太一样，这个上下运动速度无法匹配观察者模式下的水平速度调节，强制锁速度

哈哈，确实没想到这一点。
直接使这个选项只影响创造模式下的玩家可以吗？（毕竟是**creative**UpwardsSpeed）

**Comment by vocaloidkiss** [comment]
可以搬过来tweakeroo的commite或者直接重写这个功能，只影响创造模式的话不如加个开关，能配置不去覆盖飞行速度

**Comment by lovexyn0827** [comment]
> 可以搬过来tweakeroo的commite或者直接重写这个功能，只影响创造模式的话不如加个开关，能配置不去覆盖飞行速度

现在的解决办法是，支持将该选项的值设为NaN，并取其为默认值，表示该选项无效，不发挥作用，同时限制该选项只做用于创造模式玩家，尽可能向已有的文档靠拢。如果直接改的话，会导致版本间的兼容问题。

既然Tweakeroo有现成的轮子了，那就先只降低一下相应Mixin的优先级把控制权交给Tweakeroo，暂时不必自己写了。不过为了完整还是有可能做一个flyingSpeedScale这样的选项。

**Comment by lovexyn0827** [comment]
话说回来，这样的话，大概还得在下一个release前抽空把所有的Mixin都检查一下。

其实已经有Advanced Mixin配置功能来管理可选的Mixin了，但是一直都没有去实际去用。

**Comment by lovexyn0827** [comment]
在[0.7.0+v20231216-BETA](https://github.com/lovexyn0827/MessMod/releases/tag/0.7.0%2Bv20231216-BETA)中已修复
