### ISSUE TITLE
update for 1.17 please 

### ISSUE THREAD

**Issue by RYUKxAnime** [lovexyn0827/Minecraft-World-Manipulation-Enchantment-Mod#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A Port to the version 1.17.1 would be nice
even the version 0.4.0 would be more than enough

**Describe alternatives you've considered**

**Additional context**

**Comment by lovexyn0827** [comment]
Done.

[https://modrinth.com/mod/messmod/version/0.5.1+v20231202-BETA]()

This version is not well-tested, feel free to report bugs, if any.
